name: CI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Compile Theme
        run: |
          cp -R nightingale/*       nightingale-show/
          cp -R nightingale-child/* nightingale-show/
          cp nightingale/functions.php nightingale/style.css nightingale-show/
          cat nightingale-child/functions.php | tail -n+2 >> nightingale-show/functions.php
          cat nightingale-child/style.meta.css nightingale/style.css nightingale-child/style.css > nightingale-show/style.css

      - name: Update versions by tag
        run: |
          sed -i "s|--VERSION_TAG--|${GITHUB_REF_NAME#v}|" info.json
          sed -i "s|--VERSION_TAG--|${GITHUB_REF_NAME#v}|" nightingale-show/style.css

      - name: Compress Theme
        run: |
          zip -r theme.zip nightingale-show

      - uses: actions/upload-artifact@v4
        with:
          name: Theme Artifact
          path: src/theme.zip
          compression-level: 0

      # - name: Release new version
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh release create "${GITHUB_REF_NAME#v}" theme.zip info.json
